dota-django-project/dota/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^heroes/', include('heroes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dota-django-project/heroes/urls.py
from django.conf.urls import url
from . import views

app_name = 'hero'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /dota/album/add
    url(r'hero/add/$', views.HeroCreate.as_view(), name='hero-add'),

    # /heroes/hero/2
    url(r'hero/(?P<pk>[0-9]+)/$', views.HeroUpdate.as_view(), name='hero-update'),

    # /heroes/hero/2/delete/
    url(r'hero/(?P<pk>[0-9]+)/delete/$', views.HeroDelete.as_view(), name='hero-delete'),
]

dota-django-project/heroes/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse


class Hero(models.Model):
    CLASS_HERO = (
        ('Strength', 'Strength'),
        ('Intelligence', 'Intelligence'),
        ('Agility', 'Agility')
    )
    name = models.CharField(max_length=250)
    type = models.CharField(max_length=250)
    class_of_hero = models.CharField(max_length=15, choices=CLASS_HERO, default='Strength')
    hero_pic = models.FileField()

    def get_absolute_url(self):
        return reverse('hero:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name + '-' + self.type


class Guide(models.Model):
    hero = models.ForeignKey(Hero, on_delete=models.CASCADE)
    rating = models.CharField(max_length=2)
    guide_name = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.hero.name + '-' + self.guide_name

dota-django-project/heroes/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

dota-django-project/heroes/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.views.generic import View
from .models import Hero
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = 'heroes/index.html'
    context_object_name = 'all_heroes'

    def get_queryset(self):
        return Hero.objects.all()


class DetailView(generic.DetailView):
    model = Hero
    template_name = 'heroes/detail.html'


class HeroCreate(CreateView):
    model = Hero
    fields = ['name', 'type', 'class_of_hero', 'hero_pic']


class HeroUpdate(UpdateView):
    model = Hero
    fields = ['name', 'type', 'class_of_hero', 'hero_pic']


class HeroDelete(DeleteView):
    model = Hero
    success_url = reverse_lazy('hero:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'heroes/registration_form.html'

    # blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # Process for data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # Cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns user objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('hero:index')

        return render(request, self.template_name, {'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('hero:index')

dota-django-project/heroes/templates/heroes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Dota 2{% endblock %}</title>
    {% load staticfiles %}
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'heroes/style.css' %}"/>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!--Logo-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'hero:index' %}">Dota 2</a>
        </div>

        <!--Items in nav bar -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'hero:index' %}">
                        <span class="glyphicon glyphicon-tower" aria-hidden="true"></span>&nbsp; Heroes
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>&nbsp; Guides
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value=""/>
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'hero:hero-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Hero
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'hero:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

dota-django-project/heroes/templates/heroes/detail.html
{% extends 'heroes/base.html' %}
{% block title %}Detail{% endblock %}
{% block body %}


<img src="{{ hero.hero_pic.url }}">
<h1>{{ hero.name }}</h1>
<h2>{{ hero.type }}</h2>
<h2>{{ hero.class_of_hero }}</h2>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
    {% csrf_token %}
    {% for guide in hero.guide_set.all %}
            {{ guide.guide_name }}
            {% if guide.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png"/>
            {% endif %}
        <br>
    {% endfor %}


{% endblock %}

dota-django-project/heroes/templates/heroes/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

dota-django-project/heroes/templates/heroes/hero_form.html
{% extends 'heroes/base.html' %}
{% block title %}Add a New hero{% endblock %}
{% block hero_active %}active{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">

            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'heroes/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

dota-django-project/heroes/templates/heroes/index.html
{% extends 'heroes/base.html' %}
{% block title %}Heroes List{% endblock %}

{% block body %}
    <div class="heroes-container container-fluid">
        <!--Heroes-->
        <div class="row">
            <div class="col-sm-12">
                <h3>{{ user.username }}'s Heroes</h3>
            </div>
            {% if all_heroes %}
                {% for hero in all_heroes %}
                    <div class="col-sm-4 col-lg-2">
                        <div class="thumbnail">
                            <a href="{% url 'hero:detail' hero.id %}">
                                <img src="{{ hero.hero_pic.url }}" class="img-responsive">
                            </a>
                            <div class="caption wrapper">
                                <h2>{{ hero.name }}</h2>

                                <!--View Details-->
                                <a href="{% url 'hero:detail' hero.id %}" class="btn btn-primary btn-sm"
                                   role="button">View</a>
                                <!--Delete Hero-->
                                <form action="{% url 'hero:hero-delete' hero.id %}" method="post"
                                      style="display: inline">
                                    {% csrf_token %}
                                    <input type="hidden" name="hero_id" value="{{ hero.id }}"/>
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>
                                <!--Favorite Hero-->
                                <a href="#"
                                   class="btn btn-default btn-sm btn-favorite"
                                   role="button">
                                    <span class="glyphicon glyphicon-star"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                    {% cycle '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                {% endfor %}
            {% else %}
                <div class="col-sm-12">
                    <br>
                    <a href="{% url 'hero:hero-add' %}">
                        <button type="button" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Hero
                        </button>
                    </a>
                </div>
            {% endif %}
        </div>


    </div>
{% endblock %}

dota-django-project/heroes/templates/heroes/registration_form.html
{% extends 'heroes/base.html' %}
{% block title %}Register{% endblock %}
{% block hero_active %}active{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">

            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Create a New Account</h3>
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'heroes/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}